### ISSUE TITLE
Add support for relaxng and schematron validation

### ISSUE THREAD

**Issue by andya9** [AtomLinter/linter-xmllint#29]
Sequel to issue #3.
Support for dtd and xml schema has been implemented by @dirk-thomas; relaxng and schematron are missing.
As pointed out by @adunning, those validators are called like this:
><?xml-model href="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng"
>    schematypens="http://relaxng.org/ns/structure/1.0"?>
><?xml-model href="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng"
>    schematypens="http://purl.oclc.org/dsdl/schematron"?>

**Comment by adunning** [comment]
As noted in #30, adding `xml-model` support is the first step. One minor issue is that there's a bug in the current release of `xmllint` that causes it to hang when validating some files against a Relax NG schema; we're discussing this at https://github.com/TEIC/TEI-Simple/issues/24. I've always used [Jing](http://www.thaiopensource.com/relaxng/jing.html) and [Probatron4J](http://www.probatron.org/probatron4j.html) for validating Relax NG and Schematron (the latter can also be done with XSLT); could these perhaps be used instead of `xmllint` if it is detected that they are available on the user system? (They can be installed quite easily using Homebrew on OS X.)

**Comment by dirk-thomas** [comment]
I implemented support for Relax NG schemas in #37. It would be great if you could try the branch and confirm that it works (or doesn't) for you.

After this schematron support should be very easy to add.

Since this package is called `linter-xmllint` I think using something else then `xmllint` is out of scope.

**Comment by andya9** [comment]
I tried it, it works perfectly! 
Thank’you very much!! :balloon:

**Comment by dirk-thomas** [comment]
Thank you for checking!

**Comment by dirk-thomas** [comment]
I should keep this open for `schematron` support.

**Comment by dirk-thomas** [comment]
@andya9 Since I am not familiar with schematron could you please provide a simple schema similar to the existing dtd / xsd / rng ones in the test folder? Based on that I should be able to implement and test support for schematron easily.

**Comment by andya9** [comment]
@dirk-thomas Sadly I never used schematron either. Maybe @adunning  ?

**Comment by dirk-thomas** [comment]
I implemented support for schematron in #39. It would be great if you could try the branch and confirm that it works (or doesn't) for you.
